# Generated by Django 4.2.6 on 2023-10-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinanceApi',
        ),
        migrations.AddField(
            model_name='stock',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
