# Generated by Django 4.2.6 on 2024-07-25 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker_app', '0003_stock_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_set', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_tracker_app.stock')),
            ],
            options={
                'verbose_name_plural': 'Stock Price Thresholds',
            },
        ),
    ]
